export {
  type PresetId,
  PRESET_IDS,
  PRESETS,
  type PresetMeta,
  verticalSliceConfig,
  slice,
  blueprintDepRules,
  nxModuleBoundariesOptions,
  sameApp,
  appOf,
  inAnyFeat,
  type VerticalPreset,
  type VerticalSliceOptions,
  hexagonalConfig,
  hexSlice,
  type HexPreset,
  type HexagonalOptions,
  configTemplate,
} from './presets';
