import { formatFiles, type GeneratorCallback, logger, type Tree } from '@nx/devkit';
import { readFileSync } from 'node:fs';
import { isAbsolute, join } from 'node:path';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import {
  CLIENT_PARTS,
  GENERATED_FOLDER,
  LIBS_DIR,
  parseClientPath,
  projectNameFor,
  SHARED_SCOPE,
} from '@blueprint/tooling-conventions';
import { adapterRegistry, type ClientEntry, DEFAULT_ADAPTER } from '../../plugin/openapi-clients';
import { addClientEntry, clientExportPrefix, readClientsJson } from '../../clients';
import { assertKebabCase, assertSliceExists } from '@blueprint/tooling-conventions/tree';

export interface ClientGeneratorSchema {
  /** folder name, e.g. `pet-client` */
  name: string;
  /** owning domain (libs/<domain>/generated/<name>); omitted = shared (libs/generated/<name>) */
  domain?: string;
  /** spec: a file (workspace-relative or absolute, .yaml/.yml/.json) or an http(s) URL (downloaded once) */
  spec: string;
  /** source for update-spec; default: `spec` when it is a URL */
  url?: string;
  /** adapter id (packages/tooling/openapi/src/facade/adapters/registry.json); default: defaultAdapter */
  adapter?: string;
  skipFormat?: boolean;
}

const isUrl = (value: string): boolean => /^https?:\/\//.test(value);

/** Committed spec file name + content: a URL is normalized to YAML (as update-spec does), a file is kept as is. */
async function loadSpec(tree: Tree, spec: string, url: string | undefined, projectName: string) {
  let text: string;
  let format: 'yaml' | 'json';
  if (isUrl(spec)) {
    const response = await fetch(spec);
    if (!response.ok) throw new Error(`GET ${spec}: ${response.status}`);
    text = await response.text();
    format = 'yaml';
  } else {
    // workspace-relative (read through the tree) or anywhere on disk
    text = tree.exists(spec)
      ? (tree.read(spec, 'utf-8') ?? '')
      : readFileSync(isAbsolute(spec) ? spec : join(tree.root, spec), 'utf-8');
    format = /\.json$/i.test(spec) ? 'json' : 'yaml';
  }
  let document: { openapi?: string; paths?: Record<string, unknown> };
  try {
    document = parseYaml(text);
  } catch (error) {
    throw new Error(`${spec}: no valid YAML/JSON (${(error as Error).message})`);
  }
  if (!/^3\./.test(String(document?.openapi ?? '')) || !Object.keys(document.paths ?? {}).length) {
    throw new Error(`${spec}: not an OpenAPI 3.x spec with at least one path`);
  }
  if (!isUrl(spec)) return { file: `openapi.${format}`, content: text.endsWith('\n') ? text : `${text}\n` };
  const header = [
    `# Source: ${url ?? spec}`,
    `# Update: nx run ${projectName}:update-spec (overwrites this file, normalized). Committed, the only source for generate.`,
  ];
  return {
    file: 'openapi.yaml',
    content: [...header, stringifyYaml(document, { lineWidth: 0, aliasDuplicateObjects: false })].join('\n'),
  };
}

/**
 * New OpenAPI client: spec file, the libs types/api/core/testing (only src/index.ts, the code is
 * generated into src/generated by the `generate` targets), entry in openapi-clients.json.
 */
export async function clientGenerator(tree: Tree, options: ClientGeneratorSchema): Promise<GeneratorCallback> {
  assertKebabCase(options.name, 'Client');
  if (options.name === GENERATED_FOLDER) throw new Error(`"${GENERATED_FOLDER}" is reserved.`);
  if (options.domain !== undefined && options.domain !== SHARED_SCOPE) assertSliceExists(tree, options.domain);
  const domain = options.domain && options.domain !== SHARED_SCOPE ? options.domain : undefined;
  const clientPath = domain ? `${domain}/${GENERATED_FOLDER}/${options.name}` : `${GENERATED_FOLDER}/${options.name}`;
  const client = parseClientPath(clientPath);
  if (!client) throw new Error(`${LIBS_DIR}/${clientPath}: not a client path`);
  if (tree.exists(`${LIBS_DIR}/${clientPath}`)) throw new Error(`${LIBS_DIR}/${clientPath} exists already`);
  if (readClientsJson(tree).clients?.[clientPath])
    throw new Error(`openapi-clients.json has an entry "${clientPath}" already`);
  if (options.adapter && !adapterRegistry()[options.adapter]) {
    throw new Error(`Unknown adapter "${options.adapter}" — known: ${Object.keys(adapterRegistry()).join(', ')}`);
  }

  const projectName = projectNameFor(clientPath);
  const url = options.url ?? (isUrl(options.spec) ? options.spec : undefined);
  const spec = await loadSpec(tree, options.spec, url, projectName);
  tree.write(`${LIBS_DIR}/${clientPath}/${spec.file}`, spec.content);
  for (const part of Object.keys(CLIENT_PARTS)) {
    tree.write(`${LIBS_DIR}/${clientPath}/${part}/src/index.ts`, "export * from './generated';\n");
  }
  const defaultAdapter = readClientsJson(tree).defaultAdapter ?? DEFAULT_ADAPTER;
  const entry: ClientEntry = {
    ...(url ? { url } : {}),
    ...(options.adapter && options.adapter !== defaultAdapter ? { adapter: options.adapter } : {}),
  };
  addClientEntry(tree, clientPath, entry);

  if (!options.skipFormat) await formatFiles(tree);
  const alias = `@blueprint/${clientPath}`;
  const prefix = clientExportPrefix(options.name);
  return () => {
    logger.info(
      `Client ${projectName}: ${LIBS_DIR}/${clientPath}/{${spec.file},${Object.keys(CLIENT_PARTS).join(',')}}, entry in openapi-clients.json.`,
    );
    logger.info(`Generate: nx run-many -t generate (build/lint/test/typecheck do it on their own).`);
    logger.info(
      `Use: ${alias}/api (services) + /types in the ${domain ?? 'shared'} api layer (the port), specs: ${alias}/testing (${prefix}Handlers, ${prefix}Http).`,
    );
  };
}

export default clientGenerator;
