/**
 * Facade end-to-end per adapter against the fixture spec (test/fixtures/things.yaml) in a fixture workspace:
 * classification, split into types/api/core, imports rewritten to the part aliases, barrels (incl. duplicate
 * export names), lint header, determinism (second run byte-identical) and the generated code compiles
 * against the aliases.
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { generateClient, resolveClient } from '../../src/facade/facade.mjs';
import {
  addClient,
  createWorkspace,
  filesBelow,
  fixture,
  hashTree,
  read,
  removeWorkspace,
  typecheck,
} from '../helpers.mjs';

const HEADER =
  '/* eslint-disable */\n/* eslint-enable @nx/enforce-module-boundaries, no-restricted-imports */\n// Generated by @blueprint/tooling (openapi, adapter ';

interface AdapterCase {
  adapter: string;
  options?: Record<string, unknown>;
  /** files the classification puts into each part (subset check) */
  expected: { types: string[]; api: string[]; core: string[] };
  /** a line of the core barrel proving the duplicate-name resolution (hey-api only) */
  conflictLine?: string;
}

const openapiToolsFiles = {
  types: ['model/models.ts', 'model/owner.ts', 'model/thing-kind.ts', 'model/thing.ts'],
  api: ['api/api.ts', 'api/owners.service.ts', 'api/things.service.ts'],
  core: ['configuration.ts', 'encoder.ts', 'variables.ts'],
};
const heyApiFiles = {
  types: ['types.gen.ts'],
  api: ['sdk.gen.ts'],
  core: ['client.gen.ts', 'client/index.ts'],
};

const cases: AdapterCase[] = [
  { adapter: 'openapi-tools', expected: openapiToolsFiles },
  { adapter: 'hey-api', expected: heyApiFiles, conflictLine: '// without ' },
  { adapter: 'nx-plugin-openapi', expected: openapiToolsFiles },
  { adapter: 'nx-plugin-openapi', options: { plugin: 'hey-api' }, expected: heyApiFiles, conflictLine: '// without ' },
];

describe.each(cases)('facade with adapter $adapter $options', ({ adapter, options, expected, conflictLine }) => {
  let root: string;
  const clientPath = 'shop/generated/things-client';
  const part = (name: string) => `libs/${clientPath}/${name}/src/generated`;
  let written: Record<string, number>;

  beforeAll(async () => {
    root = createWorkspace(`facade-${adapter}`);
    addClient(root, clientPath, { entry: { adapter, ...(options ? { options } : {}) } });
    written = (await generateClient(resolveClient(root, clientPath), root)) as Record<string, number>;
  });
  afterAll(() => removeWorkspace(root));

  it('splits the classified output into types / api / core (only index.ts committed)', () => {
    for (const name of ['types', 'api', 'core'] as const) {
      const files = filesBelow(`${root}/${part(name)}`);
      expect(files).toEqual(expect.arrayContaining([...expected[name], 'index.ts']));
      expect(written[name]).toBe(files.length - 1);
    }
    // dropped: the generator's own barrel/module, README, metadata
    expect(filesBelow(`${root}/${part('core')}`)).not.toContain('api.module.ts');
    expect(filesBelow(`${root}/${part('types')}`).some((file) => file.startsWith('api/'))).toBe(false);
  });

  it('rewrites imports into another part to the part alias, keeps imports inside a part relative', () => {
    const apiSources = filesBelow(`${root}/${part('api')}`)
      .filter((file) => file !== 'index.ts')
      .map((file) => read(root, `${part('api')}/${file}`))
      .join('\n');
    expect(apiSources).toContain(`'@blueprint/${clientPath}/types'`);
    expect(apiSources).toContain(`'@blueprint/${clientPath}/core'`);
    expect(apiSources).not.toMatch(/from '\.\.\/(model|configuration|client)/);
    expect(apiSources).not.toContain('types.gen');
  });

  it('writes a barrel per part and the lint header on every file', () => {
    for (const name of ['types', 'api', 'core']) {
      const dir = `${root}/${part(name)}`;
      for (const file of filesBelow(dir)) expect(read(dir, file).startsWith(HEADER)).toBe(true);
      expect(read(dir, 'index.ts')).toMatch(/export \* from '\.\//);
    }
    if (conflictLine) expect(read(root, `${part('core')}/index.ts`)).toContain(conflictLine);
  });

  it('is deterministic: a second run is byte-identical', async () => {
    const before = hashTree(`${root}/libs`);
    await generateClient(resolveClient(root, clientPath), root);
    expect(hashTree(`${root}/libs`)).toEqual(before);
  });

  it('compiles against the aliases (strict, like libs/tsconfig.json)', () => {
    const indexFiles = ['types', 'api', 'core'].map((name) => `libs/${clientPath}/${name}/src/index.ts`);
    expect(typecheck(root, indexFiles)).toEqual([]);
  });
});

describe('facade: registry and options', () => {
  let root: string;
  beforeAll(() => {
    root = createWorkspace('facade-options');
  });
  afterAll(() => removeWorkspace(root));

  it('merges the client options over the adapter defaults (openapi-tools: providedIn)', async () => {
    addClient(root, 'generated/any-client', { entry: { options: { providedIn: 'any' } } });
    await generateClient(resolveClient(root, 'generated/any-client'), root);
    const service = read(root, 'libs/generated/any-client/api/src/generated/api/things.service.ts');
    expect(service).toContain("providedIn: 'any'");
    // untouched defaults stay: kebab-case file names, single request parameter
    expect(service).toContain('ListThingsRequestParams');
  });

  it('a spec without models: the types part is only the empty generator barrel, skipped in the index, compiles', async () => {
    addClient(root, 'generated/ping-client', { spec: fixture('no-models.yaml'), entry: { adapter: 'openapi-tools' } });
    const written = (await generateClient(resolveClient(root, 'generated/ping-client'), root)) as Record<
      string,
      number
    >;
    expect(written.types).toBe(1);
    expect(filesBelow(`${root}/libs/generated/ping-client/types/src/generated`)).toEqual([
      'index.ts',
      'model/models.ts',
    ]);
    expect(read(root, 'libs/generated/ping-client/types/src/generated/index.ts')).toMatch(/\nexport \{\};\n$/);
    const indexFiles = ['types', 'api', 'core'].map((name) => `libs/generated/ping-client/${name}/src/index.ts`);
    expect(typecheck(root, indexFiles)).toEqual([]);
  });

  it('fails when the adapter delivers files for a part without lib', async () => {
    addClient(root, 'generated/partial-client', { parts: ['api', 'core'], entry: { adapter: 'hey-api' } });
    await expect(generateClient(resolveClient(root, 'generated/partial-client'), root)).rejects.toThrow(
      /types\/src\/index\.ts missing, the adapter delivers 1 files/,
    );
  });
});
