/**
 * Testing generation (openapi-typescript, orval msw + faker, openapi-msw) from the fixture spec, and the
 * generated handlers really answering through msw 3 in Node (setupServer) with data shaped by the spec.
 */
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { resolveClient } from '../../src/facade/facade.mjs';
import { camelCase, generateTestingLib } from '../../src/testing/testing.mjs';
import {
  addClient,
  createWorkspace,
  filesBelow,
  fixture,
  hashTree,
  read,
  removeWorkspace,
  typecheck,
} from '../helpers.mjs';

const HEADER_START =
  '/* eslint-disable */\n/* eslint-enable @nx/enforce-module-boundaries, no-restricted-imports */\n// Generated by @blueprint/tooling (openapi, testing)';

describe('testing lib generation', () => {
  let root: string;
  const clientPath = 'generated/things-client';
  const generatedDir = () => join(root, 'libs', clientPath, 'testing/src/generated');
  let result: { baseUrl: string; files: number };

  beforeAll(async () => {
    root = createWorkspace('testing');
    addClient(root, clientPath);
    result = await generateTestingLib(resolveClient(root, clientPath), root);
  });
  afterAll(() => removeWorkspace(root));

  it('writes schema, mocks, model, typed http, default handlers and a barrel — all with the header', () => {
    const files = filesBelow(generatedDir());
    expect(files).toEqual(expect.arrayContaining(['schema.ts', 'mocks.ts', 'http.ts', 'handlers.ts', 'index.ts']));
    expect(files.some((file) => file.startsWith('model/'))).toBe(true);
    expect(result).toEqual({ baseUrl: 'http://api.test/v1', files: files.length });
    for (const file of files) expect(read(generatedDir(), file).startsWith(HEADER_START)).toBe(true);
    expect(read(generatedDir(), 'http.ts')).toContain('export const thingsClientBaseUrl = "http://api.test/v1";');
    expect(read(generatedDir(), 'handlers.ts')).toContain(
      'export const thingsClientHandlers: HttpHandler[] = getThingsAPIMock();',
    );
  });

  it('is deterministic and compiles', async () => {
    const before = hashTree(generatedDir());
    await generateTestingLib(resolveClient(root, clientPath), root);
    expect(hashTree(generatedDir())).toEqual(before);
    expect(typecheck(root, [`libs/${clientPath}/testing/src/index.ts`])).toEqual([]);
  });

  it('the generated handlers answer through msw (Node) with data shaped by the spec', async () => {
    const { setupServer } = await import('msw/node');
    const testing = await import(pathToFileURL(join(generatedDir(), 'index.ts')).href);
    const server = setupServer(...testing.thingsClientHandlers);
    server.listen({ onUnhandledFrame: 'error' });
    try {
      // response example of the spec
      const things = await (await fetch('http://api.test/v1/things')).json();
      expect(things).toEqual([{ id: 't-1', name: 'Lamp', kind: 'tool', owner: { id: 'o-1', name: 'Ada' } }]);
      // no example: faker fills the schema (required props, enum, property examples)
      const thing = (await (await fetch('http://api.test/v1/things/t-9')).json()) as { kind: string };
      expect(thing).toMatchObject({ id: 't-1', name: 'Lamp' });
      expect(['tool', 'toy']).toContain(thing.kind);
      const owners = (await (await fetch('http://api.test/v1/owners')).json()) as unknown[];
      expect(Array.isArray(owners)).toBe(true);
      for (const owner of owners) expect(owner).toEqual({ id: 'o-1', name: 'Ada' });

      // typed openapi-msw http overrides a default handler per test
      type Resolver = (info: {
        params: { id: string };
        response: (status: number) => { json: (body: object) => Response };
      }) => Response;
      const http = testing.thingsClientHttp as { get: (path: string, resolver: Resolver) => never };
      server.use(
        http.get('/things/{id}', ({ params, response }) =>
          response(200).json({ id: params.id, name: 'Override', kind: 'toy' }),
        ),
      );
      expect(await (await fetch('http://api.test/v1/things/x-1')).json()).toEqual({
        id: 'x-1',
        name: 'Override',
        kind: 'toy',
      });
    } finally {
      server.close();
    }
  });

  it('camelCase: client name → export prefix', () => {
    expect(camelCase('pet-client')).toBe('petClient');
    expect(camelCase('a-b2-c')).toBe('aB2C');
  });
});

describe('testing lib generation: errors', () => {
  let root: string;
  beforeAll(() => {
    root = createWorkspace('testing-errors');
  });
  afterAll(() => removeWorkspace(root));

  it('fails without spec file', async () => {
    const client = {
      name: 'x-client',
      placement: 'shared' as const,
      spec: { file: 'libs/generated/x-client/openapi.yaml' },
    };
    await expect(generateTestingLib(client, root)).rejects.toThrow('libs/generated/x-client/openapi.yaml missing');
  });

  it('fails without the committed testing index.ts', async () => {
    addClient(root, 'generated/no-testing-client', { parts: ['types', 'api', 'core'] });
    await expect(generateTestingLib(resolveClient(root, 'generated/no-testing-client'), root)).rejects.toThrow(
      "testing/src/index.ts missing (export * from './generated';)",
    );
  });

  it('fails for a spec without operations (orval produces no handlers)', async () => {
    addClient(root, 'generated/empty-client', {
      spec: 'openapi: 3.0.3\ninfo: { title: Empty, version: 1.0.0 }\npaths: {}\n',
    });
    await expect(generateTestingLib(resolveClient(root, 'generated/empty-client'), root)).rejects.toThrow(
      'orval produced no msw handlers',
    );
  });

  it('a spec without servers gets baseUrl ""', async () => {
    addClient(root, 'booking/generated/ping-client', { spec: fixture('no-models.yaml').replace(/servers:\n.*\n/, '') });
    const result = await generateTestingLib(resolveClient(root, 'booking/generated/ping-client'), root);
    expect(result.baseUrl).toBe('');
    expect(read(root, 'libs/booking/generated/ping-client/testing/src/generated/http.ts')).toContain(
      'export const pingClientBaseUrl = "";',
    );
  });
});
